
configfile: os.path.join(workflow.basedir, '../', 'config', 'config.yaml')

samples, = glob_wildcards(os.path.join(config['input'],'{sample}.gbk'))
inDir = config['input']

allTargets = [
    # expand(os.path.join(inDir,'{sample}.consec_strand.tsv'), sample=samples),
    # expand(os.path.join(inDir,'{sample}.consec_frame.tsv'), sample=samples),
    # expand(os.path.join(inDir,'{sample}.consec_overlap.tsv'), sample=samples),
    # expand(os.path.join(inDir,'{sample}.potential-alt-stops.tsv'), sample=samples),
    expand(os.path.join(inDir,'{sample}.{suff}'), sample=samples, suff=['orfm.faa','orfm.fna','gaps.bed']),
    os.path.join(inDir, 'summary.consec.tsv')
]

include: 'rules/strandSwaps.smk'
include: 'rules/altStops.smk'

# Mark target rules
target_rules = []
def targetRule(fn):
    assert fn.__name__.startswith('__')
    target_rules.append(fn.__name__[2:])
    return fn

@targetRule
rule all:
    input:
        allTargets

@targetRule
rule print_targets:
    run:
        print("\nTop level rules are: \n", file=sys.stderr)
        print("* " + "\n* ".join(target_rules) + "\n\n", file=sys.stderr)
